$(document).ready(function(){
   $('.slider').slick({
      arrows:false,
      dots:false,
      slidesToShow:6,
      speed:15000,
      infinite:true,
      initialSlide:0,
      autoplay:true,
      autoplaySpeed:0
   });
});